@echo off
title FitAI Launcher
cd /d "%~dp0"
echo [1/3] Generowanie najnowszej wersji strony...
python generate_html_complete.py
echo [2/3] Uruchamianie Backend API w nowym oknie...
start "FitAI Backend" cmd /k "uvicorn fitai_api:app --reload --port 8000"
echo [3/3] Oczekiwanie na start serwera...
timeout /t 3
echo Otwieranie strony w przegladarce...
start index.html