"""Initial schema: users, daily_logs, exercise_results, drill_results

Revision ID: f9fd63cba750
Revises: 
Create Date: 2026-05-13 18:55:19.752581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fd63cba750'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_logs_user_date'), table_name='daily_logs')
    op.alter_column('drill_results', 'time_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('drill_results', 'distance_meters',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('drill_results', 'weight_kg',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_drill_results_user_date'), table_name='drill_results')
    op.drop_index(op.f('ix_exercise_results_user_date'), table_name='exercise_results')
    op.drop_index(op.f('ix_exercise_results_user_name'), table_name='exercise_results')
    op.drop_column('users', 'xp_total')
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), nullable=True))
    op.add_column('users', sa.Column('xp_total', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.create_index(op.f('ix_exercise_results_user_name'), 'exercise_results', ['user_id', 'exercise_name'], unique=False)
    op.create_index(op.f('ix_exercise_results_user_date'), 'exercise_results', ['user_id', 'session_date'], unique=False)
    op.create_index(op.f('ix_drill_results_user_date'), 'drill_results', ['user_id', 'session_date'], unique=False)
    op.alter_column('drill_results', 'weight_kg',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('drill_results', 'distance_meters',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('drill_results', 'time_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_index(op.f('ix_daily_logs_user_date'), 'daily_logs', ['user_id', 'log_date'], unique=False)
    # ### end Alembic commands ###
